export const Permissions = {
  DRAW_READ_ADMIN: 'draw.read.admin',
  DRAW_CREATE: 'draw.create',
  DRAW_UPDATE: 'draw.update',
  DRAW_OPEN_SALES: 'draw.open_sales',
  DRAW_CLOSE_SALES: 'draw.close_sales',
  DRAW_BUILD_SNAPSHOT: 'draw.build_snapshot',
  DRAW_FINALIZE_SNAPSHOT: 'draw.finalize_snapshot',
  DRAW_REQUEST_RANDOMNESS: 'draw.request_randomness',
  DRAW_SELECT_WINNERS: 'draw.select_winners',
  DRAW_CANCEL: 'draw.cancel',
  DRAW_PUBLISH: 'draw.publish',
  USER_READ_ADMIN: 'user.read.admin',
  PURCHASE_READ_ADMIN: 'purchase.read.admin',
  TICKET_READ_ADMIN: 'ticket.read.admin',
  FINANCE_READ_ADMIN: 'finance.read.admin',
  PURCHASE_REVIEW_ADMIN: 'purchase.review.admin',
  PURCHASE_CANCEL_ADMIN: 'purchase.cancel.admin',
  PURCHASE_REFUND_ADMIN: 'purchase.refund.admin',
} as const;
