export const AuditActions = {
  AUTH_LOGIN_SUCCEEDED:
    'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED:
    'AUTH_LOGIN_FAILED',
  AUTH_REGISTRATION_SUCCEEDED:
    'AUTH_REGISTRATION_SUCCEEDED',
  AUTH_LOGOUT_SUCCEEDED:
    'AUTH_LOGOUT_SUCCEEDED',
  AUTH_TOKEN_REFRESHED:
    'AUTH_TOKEN_REFRESHED',
  AUTH_EMAIL_VERIFIED:
    'AUTH_EMAIL_VERIFIED',
  AUTH_PASSWORD_RESET_REQUESTED:
    'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED:
    'AUTH_PASSWORD_RESET_COMPLETED',

  DRAW_CREATED:
    'DRAW_CREATED',
  DRAW_UPDATED:
    'DRAW_UPDATED',
  DRAW_SALES_OPENED:
    'DRAW_SALES_OPENED',
  DRAW_SALES_CLOSED:
    'DRAW_SALES_CLOSED',
  DRAW_CANCELLED:
    'DRAW_CANCELLED',
  DRAW_PUBLISHED:
    'DRAW_PUBLISHED',
  DRAW_RANDOMNESS_VERIFIED:
    'DRAW_RANDOMNESS_VERIFIED',
  DRAW_RANDOMNESS_REPLAYED:
    'DRAW_RANDOMNESS_REPLAYED',
  DRAW_WINNER_SELECTION_COMPLETED:
    'DRAW_WINNER_SELECTION_COMPLETED',
  DRAW_WINNER_SELECTION_REPLAYED:
    'DRAW_WINNER_SELECTION_REPLAYED',

  SNAPSHOT_BUILD_STARTED:
    'SNAPSHOT_BUILD_STARTED',
  SNAPSHOT_BUILD_COMPLETED:
    'SNAPSHOT_BUILD_COMPLETED',
  SNAPSHOT_FINALIZED:
    'SNAPSHOT_FINALIZED',

  PURCHASE_CREATED:
    'PURCHASE_CREATED',
  PURCHASE_CANCELLED:
    'PURCHASE_CANCELLED',

  ADMIN_PURCHASE_MANUAL_REVIEW:

    'ADMIN_PURCHASE_MANUAL_REVIEW',

  ADMIN_PURCHASE_CANCELLED:

    'ADMIN_PURCHASE_CANCELLED',


  ADMIN_PURCHASE_REFUND_REQUESTED:


    'ADMIN_PURCHASE_REFUND_REQUESTED',



  AUTHORIZATION_DENIED:
    'AUTHORIZATION_DENIED',
} as const;

export type AuditAction =
  (typeof AuditActions)[keyof typeof AuditActions];

export const AuditEntityTypes = {
  USER: 'USER',
  AUTH_SESSION: 'AUTH_SESSION',
  LOTTERY_DRAW: 'LOTTERY_DRAW',
  SNAPSHOT: 'SNAPSHOT',
  RANDOMNESS_EVIDENCE:
    'RANDOMNESS_EVIDENCE',
  PURCHASE: 'PURCHASE',
  PERMISSION: 'PERMISSION',
} as const;

export type AuditEntityType =
  (typeof AuditEntityTypes)[keyof typeof AuditEntityTypes];
